name: flutter_storyblok_code_generator
description: Code generator for flutter_storyblok, generating statically typed Dart code from your Storyblok blocks.
version: 1.0.2
homepage: https://www.alster.se/
repository: https://github.com/alsterverse/flutter_storyblok/tree/main/code_generator
issue_tracker: https://github.com/alsterverse/flutter_storyblok/issues
topics:
  - storyblok
  - sdk
  - code-builder
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

executables:
  flutter_storyblok_code_generator: flutter_storyblok_code_generator

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_storyblok: ^1.0.2
  dart_style: ^2.3.6
  code_builder: ^4.10.0
  dart_casing: ^3.0.1
  http: ^1.2.1
  collection: ^1.18.0
  characters: ^1.3.0
  args: ^2.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
