name: example
description: Example app implementing Storybloks Demo Space
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  flutter_storyblok: any
  go_router: ^13.1.0
  camera: ^0.10.5+4
  sensors_plus: ^4.0.2
  share_plus: ^7.1.0
  video_player: ^2.7.2
  wave: ^0.2.2
  multiselect: ^0.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_storyblok_code_generator:
    path: ../code_generator

flutter:
  uses-material-design: true

  assets:
    - assets/
