name: flutter_storyblok
description: Integrate Storyblok with your Flutter app using this SDK and code generator.
version: 1.0.1
homepage: https://www.alster.se/
repository: https://github.com/alsterverse/flutter_storyblok
issue_tracker: https://github.com/alsterverse/flutter_storyblok/issues
topics:
  - storyblok
  - sdk

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
      sdk: flutter
  http: ^1.2.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^4.0.0
  build_runner: ^2.4.9
